// ─── DEMO DATA — Rajasthan-focused CBBO cluster ──────────────────────────────

export const DEMO_FARMERS_PER_TENANT = [
  { tenantId: 'demo-1',  tenantName: 'Marwar Kisan Samridhi FPO',    tenantCode: 'MARFPO', totalFarmers: 312, state: 'Rajasthan', district: 'Jodhpur' },
  { tenantId: 'demo-2',  tenantName: 'Shekhawati Agri Producer',      tenantCode: 'SHKFPO', totalFarmers: 278, state: 'Rajasthan', district: 'Jaipur'  },
  { tenantId: 'demo-3',  tenantName: 'Hadoti Farmers Collective',     tenantCode: 'HADFPO', totalFarmers: 195, state: 'Rajasthan', district: 'Kota'    },
  { tenantId: 'demo-4',  tenantName: 'Chambal Valley FPO',            tenantCode: 'CHAFPO', totalFarmers: 241, state: 'Rajasthan', district: 'Jodhpur' },
  { tenantId: 'demo-5',  tenantName: 'Thar Organic Producers',        tenantCode: 'THAFPO', totalFarmers: 134, state: 'Rajasthan', district: 'Bikaner' },
  { tenantId: 'demo-6',  tenantName: 'Mewar Krishi Vikas FPO',        tenantCode: 'MEWFPO', totalFarmers: 289, state: 'Rajasthan', district: 'Jodhpur' },
  { tenantId: 'demo-7',  tenantName: 'Dhundhar Kisan Producer Co.',   tenantCode: 'DHUFPO', totalFarmers: 167, state: 'Rajasthan', district: 'Jaipur'  },
  { tenantId: 'demo-8',  tenantName: 'Godwar Agri Collective',        tenantCode: 'GODFPO', totalFarmers: 148, state: 'Rajasthan', district: 'Kota'    },
  { tenantId: 'demo-9',  tenantName: 'Bikaner Dryland FPO',           tenantCode: 'BIKFPO', totalFarmers: 203, state: 'Rajasthan', district: 'Bikaner' },
  { tenantId: 'demo-10', tenantName: 'Vagad Tribal Farmers FPO',      tenantCode: 'VAGFPO', totalFarmers: 112, state: 'Rajasthan', district: 'Ajmer'   },
  { tenantId: 'demo-11', tenantName: 'Aravalli Green Producers',      tenantCode: 'ARAFPO', totalFarmers: 176, state: 'Rajasthan', district: 'Jodhpur' },
  { tenantId: 'demo-12', tenantName: 'Mewat Agri Producer Society',   tenantCode: 'MWTFPO', totalFarmers: 98,  state: 'Rajasthan', district: 'Ajmer'   },
  { tenantId: 'demo-13', tenantName: 'Brij Kisan Utpadak Sangh',      tenantCode: 'BRJFPO', totalFarmers: 221, state: 'Rajasthan', district: 'Jaipur'  },
  { tenantId: 'demo-14', tenantName: 'Malani Seed Farmers FPO',       tenantCode: 'MALFPO', totalFarmers: 143, state: 'Rajasthan', district: 'Kota'    },
  { tenantId: 'demo-15', tenantName: 'Nagar FPO Hanumangarh',         tenantCode: 'NAGFPO', totalFarmers: 258, state: 'Rajasthan', district: 'Bikaner' },
];

export const DEMO_REVENUE = {
  revenuePerTenant: [
    { tenantId: 'demo-1',  tenantName: 'Marwar Kisan Samridhi FPO',  tenantCode: 'MARFPO', salesRevenue: 875000,  procurementExpense: 620000, netRevenue: 255000  },
    { tenantId: 'demo-2',  tenantName: 'Shekhawati Agri Producer',    tenantCode: 'SHKFPO', salesRevenue: 740000,  procurementExpense: 510000, netRevenue: 230000  },
    { tenantId: 'demo-3',  tenantName: 'Hadoti Farmers Collective',   tenantCode: 'HADFPO', salesRevenue: 490000,  procurementExpense: 415000, netRevenue: 75000   },
    { tenantId: 'demo-4',  tenantName: 'Chambal Valley FPO',          tenantCode: 'CHAFPO', salesRevenue: 615000,  procurementExpense: 540000, netRevenue: 75000   },
    { tenantId: 'demo-5',  tenantName: 'Thar Organic Producers',      tenantCode: 'THAFPO', salesRevenue: 320000,  procurementExpense: 355000, netRevenue: -35000  },
    { tenantId: 'demo-6',  tenantName: 'Mewar Krishi Vikas FPO',      tenantCode: 'MEWFPO', salesRevenue: 810000,  procurementExpense: 590000, netRevenue: 220000  },
    { tenantId: 'demo-7',  tenantName: 'Dhundhar Kisan Producer Co.', tenantCode: 'DHUFPO', salesRevenue: 445000,  procurementExpense: 390000, netRevenue: 55000   },
    { tenantId: 'demo-8',  tenantName: 'Godwar Agri Collective',      tenantCode: 'GODFPO', salesRevenue: 380000,  procurementExpense: 410000, netRevenue: -30000  },
    { tenantId: 'demo-9',  tenantName: 'Bikaner Dryland FPO',         tenantCode: 'BIKFPO', salesRevenue: 560000,  procurementExpense: 430000, netRevenue: 130000  },
    { tenantId: 'demo-10', tenantName: 'Vagad Tribal Farmers FPO',    tenantCode: 'VAGFPO', salesRevenue: 275000,  procurementExpense: 250000, netRevenue: 25000   },
    { tenantId: 'demo-11', tenantName: 'Aravalli Green Producers',    tenantCode: 'ARAFPO', salesRevenue: 510000,  procurementExpense: 420000, netRevenue: 90000   },
    { tenantId: 'demo-12', tenantName: 'Mewat Agri Producer Society', tenantCode: 'MWTFPO', salesRevenue: 210000,  procurementExpense: 230000, netRevenue: -20000  },
    { tenantId: 'demo-13', tenantName: 'Brij Kisan Utpadak Sangh',    tenantCode: 'BRJFPO', salesRevenue: 680000,  procurementExpense: 495000, netRevenue: 185000  },
    { tenantId: 'demo-14', tenantName: 'Malani Seed Farmers FPO',     tenantCode: 'MALFPO', salesRevenue: 395000,  procurementExpense: 340000, netRevenue: 55000   },
    { tenantId: 'demo-15', tenantName: 'Nagar FPO Hanumangarh',       tenantCode: 'NAGFPO', salesRevenue: 920000,  procurementExpense: 670000, netRevenue: 250000  },
  ],
  totalSalesRevenueAllTenants:       8225000,
  totalProcurementExpenseAllTenants: 6465000,
  totalNetRevenueAllTenants:          1760000,
  averageSalesRevenue:                548333,
  averageProcurementExpense:          431000,
  averageNetRevenue:                   117333,
};

export const DEMO_FARMER_GROWTH = {
  totalGrowth: [
    { year: 2025, month: 6,  monthName: 'Jun', formatted: '2025-06', count: 412  },
    { year: 2025, month: 7,  monthName: 'Jul', formatted: '2025-07', count: 498  },
    { year: 2025, month: 8,  monthName: 'Aug', formatted: '2025-08', count: 587  },
    { year: 2025, month: 9,  monthName: 'Sep', formatted: '2025-09', count: 694  },
    { year: 2025, month: 10, monthName: 'Oct', formatted: '2025-10', count: 812  },
    { year: 2025, month: 11, monthName: 'Nov', formatted: '2025-11', count: 945  },
    { year: 2025, month: 12, monthName: 'Dec', formatted: '2025-12', count: 1089 },
    { year: 2026, month: 1,  monthName: 'Jan', formatted: '2026-01', count: 1234 },
    { year: 2026, month: 2,  monthName: 'Feb', formatted: '2026-02', count: 1398 },
    { year: 2026, month: 3,  monthName: 'Mar', formatted: '2026-03', count: 1562 },
    { year: 2026, month: 4,  monthName: 'Apr', formatted: '2026-04', count: 1741 },
    { year: 2026, month: 5,  monthName: 'May', formatted: '2026-05', count: 2865 },
  ],
  tenantWiseGrowth: [
    { tenantId: 'demo-1',  tenantName: 'Marwar Kisan Samridhi FPO',  tenantCode: 'MARFPO', growth: [{ year: 2026, month: 3, monthName: 'Mar', count: 268 }, { year: 2026, month: 4, monthName: 'Apr', count: 290 }, { year: 2026, month: 5, monthName: 'May', count: 312 }] },
    { tenantId: 'demo-2',  tenantName: 'Shekhawati Agri Producer',   tenantCode: 'SHKFPO', growth: [{ year: 2026, month: 3, monthName: 'Mar', count: 241 }, { year: 2026, month: 4, monthName: 'Apr', count: 260 }, { year: 2026, month: 5, monthName: 'May', count: 278 }] },
    { tenantId: 'demo-3',  tenantName: 'Hadoti Farmers Collective',  tenantCode: 'HADFPO', growth: [{ year: 2026, month: 3, monthName: 'Mar', count: 168 }, { year: 2026, month: 4, monthName: 'Apr', count: 181 }, { year: 2026, month: 5, monthName: 'May', count: 195 }] },
    { tenantId: 'demo-4',  tenantName: 'Chambal Valley FPO',         tenantCode: 'CHAFPO', growth: [{ year: 2026, month: 3, monthName: 'Mar', count: 210 }, { year: 2026, month: 4, monthName: 'Apr', count: 226 }, { year: 2026, month: 5, monthName: 'May', count: 241 }] },
    { tenantId: 'demo-5',  tenantName: 'Thar Organic Producers',     tenantCode: 'THAFPO', growth: [{ year: 2026, month: 3, monthName: 'Mar', count: 112 }, { year: 2026, month: 4, monthName: 'Apr', count: 123 }, { year: 2026, month: 5, monthName: 'May', count: 134 }] },
    { tenantId: 'demo-6',  tenantName: 'Mewar Krishi Vikas FPO',     tenantCode: 'MEWFPO', growth: [{ year: 2026, month: 3, monthName: 'Mar', count: 254 }, { year: 2026, month: 4, monthName: 'Apr', count: 271 }, { year: 2026, month: 5, monthName: 'May', count: 289 }] },
    { tenantId: 'demo-7',  tenantName: 'Dhundhar Kisan Producer Co.',tenantCode: 'DHUFPO', growth: [{ year: 2026, month: 3, monthName: 'Mar', count: 143 }, { year: 2026, month: 4, monthName: 'Apr', count: 155 }, { year: 2026, month: 5, monthName: 'May', count: 167 }] },
    { tenantId: 'demo-8',  tenantName: 'Godwar Agri Collective',     tenantCode: 'GODFPO', growth: [{ year: 2026, month: 3, monthName: 'Mar', count: 126 }, { year: 2026, month: 4, monthName: 'Apr', count: 137 }, { year: 2026, month: 5, monthName: 'May', count: 148 }] },
    { tenantId: 'demo-9',  tenantName: 'Bikaner Dryland FPO',        tenantCode: 'BIKFPO', growth: [{ year: 2026, month: 3, monthName: 'Mar', count: 178 }, { year: 2026, month: 4, monthName: 'Apr', count: 191 }, { year: 2026, month: 5, monthName: 'May', count: 203 }] },
    { tenantId: 'demo-10', tenantName: 'Vagad Tribal Farmers FPO',   tenantCode: 'VAGFPO', growth: [{ year: 2026, month: 3, monthName: 'Mar', count: 92  }, { year: 2026, month: 4, monthName: 'Apr', count: 102 }, { year: 2026, month: 5, monthName: 'May', count: 112 }] },
    { tenantId: 'demo-11', tenantName: 'Aravalli Green Producers',   tenantCode: 'ARAFPO', growth: [{ year: 2026, month: 3, monthName: 'Mar', count: 152 }, { year: 2026, month: 4, monthName: 'Apr', count: 164 }, { year: 2026, month: 5, monthName: 'May', count: 176 }] },
    { tenantId: 'demo-12', tenantName: 'Mewat Agri Producer Society',tenantCode: 'MWTFPO', growth: [{ year: 2026, month: 3, monthName: 'Mar', count: 80  }, { year: 2026, month: 4, monthName: 'Apr', count: 89  }, { year: 2026, month: 5, monthName: 'May', count: 98  }] },
    { tenantId: 'demo-13', tenantName: 'Brij Kisan Utpadak Sangh',   tenantCode: 'BRJFPO', growth: [{ year: 2026, month: 3, monthName: 'Mar', count: 194 }, { year: 2026, month: 4, monthName: 'Apr', count: 207 }, { year: 2026, month: 5, monthName: 'May', count: 221 }] },
    { tenantId: 'demo-14', tenantName: 'Malani Seed Farmers FPO',    tenantCode: 'MALFPO', growth: [{ year: 2026, month: 3, monthName: 'Mar', count: 121 }, { year: 2026, month: 4, monthName: 'Apr', count: 132 }, { year: 2026, month: 5, monthName: 'May', count: 143 }] },
    { tenantId: 'demo-15', tenantName: 'Nagar FPO Hanumangarh',      tenantCode: 'NAGFPO', growth: [{ year: 2026, month: 3, monthName: 'Mar', count: 223 }, { year: 2026, month: 4, monthName: 'Apr', count: 241 }, { year: 2026, month: 5, monthName: 'May', count: 258 }] },
  ],
};

export const DEMO_FARMERS_LIST = [
  { farmerId: 'f-1',  tenantId: 'demo-1',  tenantName: 'Marwar Kisan Samridhi FPO',  firstName: 'Ramesh',    lastName: 'Choudhary',  mobile: '9414201101', village: 'Tinwari'    },
  { farmerId: 'f-2',  tenantId: 'demo-1',  tenantName: 'Marwar Kisan Samridhi FPO',  firstName: 'Bhura',     lastName: 'Singh',      mobile: '9414201102', village: 'Balesar'    },
  { farmerId: 'f-3',  tenantId: 'demo-1',  tenantName: 'Marwar Kisan Samridhi FPO',  firstName: 'Mangi Lal', lastName: 'Patel',      mobile: '9414201103', village: 'Pipar'      },
  { farmerId: 'f-4',  tenantId: 'demo-2',  tenantName: 'Shekhawati Agri Producer',   firstName: 'Hanuman',   lastName: 'Sharma',     mobile: '9414202101', village: 'Sikar'      },
  { farmerId: 'f-5',  tenantId: 'demo-2',  tenantName: 'Shekhawati Agri Producer',   firstName: 'Narayan',   lastName: 'Meena',      mobile: '9414202102', village: 'Fatehpur'   },
  { farmerId: 'f-6',  tenantId: 'demo-2',  tenantName: 'Shekhawati Agri Producer',   firstName: 'Suresh',    lastName: 'Yadav',      mobile: '9414202103', village: 'Laxmangarh' },
  { farmerId: 'f-7',  tenantId: 'demo-3',  tenantName: 'Hadoti Farmers Collective',  firstName: 'Rajendra',  lastName: 'Gupta',      mobile: '9414203101', village: 'Kota'       },
  { farmerId: 'f-8',  tenantId: 'demo-3',  tenantName: 'Hadoti Farmers Collective',  firstName: 'Dinesh',    lastName: 'Verma',      mobile: '9414203102', village: 'Baran'      },
  { farmerId: 'f-9',  tenantId: 'demo-4',  tenantName: 'Chambal Valley FPO',         firstName: 'Mohan',     lastName: 'Rajput',     mobile: '9414204101', village: 'Sawai Madhopur' },
  { farmerId: 'f-10', tenantId: 'demo-4',  tenantName: 'Chambal Valley FPO',         firstName: 'Gopal',     lastName: 'Jat',        mobile: '9414204102', village: 'Gangapur'   },
  { farmerId: 'f-11', tenantId: 'demo-5',  tenantName: 'Thar Organic Producers',     firstName: 'Jeevan',    lastName: 'Ram',        mobile: '9414205101', village: 'Barmer'     },
  { farmerId: 'f-12', tenantId: 'demo-5',  tenantName: 'Thar Organic Producers',     firstName: 'Bhagwan',   lastName: 'Das',        mobile: '9414205102', village: 'Sheo'       },
  { farmerId: 'f-13', tenantId: 'demo-6',  tenantName: 'Mewar Krishi Vikas FPO',    firstName: 'Pratap',    lastName: 'Singh',      mobile: '9414206101', village: 'Udaipur'    },
  { farmerId: 'f-14', tenantId: 'demo-6',  tenantName: 'Mewar Krishi Vikas FPO',    firstName: 'Keshar',    lastName: 'Lal',        mobile: '9414206102', village: 'Nathdwara'  },
  { farmerId: 'f-15', tenantId: 'demo-7',  tenantName: 'Dhundhar Kisan Producer Co.',firstName: 'Ashok',     lastName: 'Kumar',      mobile: '9414207101', village: 'Jaipur'     },
  { farmerId: 'f-16', tenantId: 'demo-7',  tenantName: 'Dhundhar Kisan Producer Co.',firstName: 'Vinod',     lastName: 'Saini',      mobile: '9414207102', village: 'Chomu'      },
  { farmerId: 'f-17', tenantId: 'demo-8',  tenantName: 'Godwar Agri Collective',     firstName: 'Devilal',   lastName: 'Bishnoi',    mobile: '9414208101', village: 'Pali'       },
  { farmerId: 'f-18', tenantId: 'demo-8',  tenantName: 'Godwar Agri Collective',     firstName: 'Sohan',     lastName: 'Kumawat',    mobile: '9414208102', village: 'Sumerpur'   },
  { farmerId: 'f-19', tenantId: 'demo-9',  tenantName: 'Bikaner Dryland FPO',        firstName: 'Pappu',     lastName: 'Ram',        mobile: '9414209101', village: 'Bikaner'    },
  { farmerId: 'f-20', tenantId: 'demo-9',  tenantName: 'Bikaner Dryland FPO',        firstName: 'Teja',      lastName: 'Ram',        mobile: '9414209102', village: 'Nokha'      },
  { farmerId: 'f-21', tenantId: 'demo-10', tenantName: 'Vagad Tribal Farmers FPO',   firstName: 'Kalu',      lastName: 'Bai',        mobile: '9414210101', village: 'Dungarpur'  },
  { farmerId: 'f-22', tenantId: 'demo-10', tenantName: 'Vagad Tribal Farmers FPO',   firstName: 'Mangu',     lastName: 'Tadvi',      mobile: '9414210102', village: 'Sagwara'    },
  { farmerId: 'f-23', tenantId: 'demo-11', tenantName: 'Aravalli Green Producers',   firstName: 'Jagdish',   lastName: 'Prajapat',   mobile: '9414211101', village: 'Ajmer'      },
  { farmerId: 'f-24', tenantId: 'demo-11', tenantName: 'Aravalli Green Producers',   firstName: 'Om',        lastName: 'Prakash',    mobile: '9414211102', village: 'Kishangarh' },
  { farmerId: 'f-25', tenantId: 'demo-12', tenantName: 'Mewat Agri Producer Society',firstName: 'Salim',     lastName: 'Khan',       mobile: '9414212101', village: 'Alwar'      },
  { farmerId: 'f-26', tenantId: 'demo-12', tenantName: 'Mewat Agri Producer Society',firstName: 'Hamid',     lastName: 'Ansari',     mobile: '9414212102', village: 'Tijara'     },
  { farmerId: 'f-27', tenantId: 'demo-13', tenantName: 'Brij Kisan Utpadak Sangh',   firstName: 'Hariom',    lastName: 'Sharma',     mobile: '9414213101', village: 'Bharatpur'  },
  { farmerId: 'f-28', tenantId: 'demo-13', tenantName: 'Brij Kisan Utpadak Sangh',   firstName: 'Ramswarup', lastName: 'Meena',      mobile: '9414213102', village: 'Deeg'       },
  { farmerId: 'f-29', tenantId: 'demo-14', tenantName: 'Malani Seed Farmers FPO',    firstName: 'Ghevar',    lastName: 'Ram',        mobile: '9414214101', village: 'Jalor'      },
  { farmerId: 'f-30', tenantId: 'demo-14', tenantName: 'Malani Seed Farmers FPO',    firstName: 'Poonam',    lastName: 'Chand',      mobile: '9414214102', village: 'Sanchore'   },
  { farmerId: 'f-31', tenantId: 'demo-15', tenantName: 'Nagar FPO Hanumangarh',      firstName: 'Mahavir',   lastName: 'Singh',      mobile: '9414215101', village: 'Hanumangarh'},
  { farmerId: 'f-32', tenantId: 'demo-15', tenantName: 'Nagar FPO Hanumangarh',      firstName: 'Surendra',  lastName: 'Kumar',      mobile: '9414215102', village: 'Sangaria'   },
];

export const DEMO_BROADCASTS = [
  { _id: 'b-1',  title: 'Mustard MSP Procurement Open — Rajasthan',      description: 'State procurement for Mustard (Sarson) at MSP ₹5,650/qtl has commenced at all 23 mandis. FPOs to register their produce before 15th June 2026.', targetRole: 'FPO Admin', createdAt: '2026-05-20T09:15:00Z' },
  { _id: 'b-2',  title: 'PM-KISAN 18th Installment Released',             description: 'The 18th installment of PM-KISAN (₹2,000) has been credited to Aadhaar-linked accounts. Farmers in Jodhpur, Bikaner and Barmer divisions to verify their DBT status.', targetRole: 'Farmer',    createdAt: '2026-05-18T11:30:00Z' },
  { _id: 'b-3',  title: 'Kharif Sowing Advisory — Bajra & Guar',         description: 'IMD Jaipur forecasts normal monsoon onset by 25th June. FPOs advised to arrange quality certified seeds of Bajra HHB-272 and Guar HG-2-20 for timely distribution.', targetRole: 'All',       createdAt: '2026-05-17T08:00:00Z' },
  { _id: 'b-4',  title: 'Agri-Infrastructure Fund — Applications Open',   description: 'NABARD AIF Scheme (3% interest subvention) applications are open for cold storage and warehouse construction. Rajasthan FPOs to apply through district NABARD office by 31st July 2026.', targetRole: 'FPO Admin', createdAt: '2026-05-14T10:00:00Z' },
  { _id: 'b-5',  title: 'Cumin (Jeera) Price Alert — Barmer & Jalor',     description: 'NCDEX cumin spot prices have risen to ₹28,500/qtl. FPOs in Barmer, Jalor and Jodhpur districts are advised to review their procurement contracts.', targetRole: 'FPO Admin', createdAt: '2026-05-12T07:45:00Z' },
  { _id: 'b-6',  title: 'Digital FPO Training Camp — June 2026',          description: 'CBBO is organising 3-day digital literacy and Tally accounting camps for FPO board members in Jaipur (12 June), Jodhpur (18 June) and Kota (24 June). Register by 5th June.', targetRole: 'FPO Admin', createdAt: '2026-05-10T13:20:00Z' },
  { _id: 'b-7',  title: 'Revised MSP for Rabi Crops 2026-27',             description: 'Government has revised MSP: Wheat ₹2,275/qtl (+₹150), Mustard ₹5,650/qtl (+₹300), Gram ₹5,440/qtl (+₹210). Rajasthan FPOs to update their procurement rate cards accordingly.', targetRole: 'All',       createdAt: '2026-05-08T09:00:00Z' },
  { _id: 'b-8',  title: 'FPO Annual ROC Compliance Reminder',             description: 'Annual returns for all registered FPCs in Rajasthan are due by 30th June 2026. SFAC compliance cell can be contacted at sfac-raj@gov.in for assistance.', targetRole: 'FPO Admin', createdAt: '2026-05-05T11:00:00Z' },
  { _id: 'b-9',  title: 'Soil Health Card — Kharif 2025-26 Ready',        description: 'New Soil Health Cards for Kharif 2025-26 season are ready. FPOs in Hanumangarh, Ganganagar and Bikaner districts to collect cards from District Agriculture Officer before 30th May.', targetRole: 'Farmer',    createdAt: '2026-05-01T10:30:00Z' },
  { _id: 'b-10', title: 'CBBO Platform Upgraded to API v2.4',             description: 'The CBBO analytics platform has been upgraded. New modules for spice crop procurement tracking and mandi price feed integration are now live. Contact helpdesk for access.', targetRole: 'All',       createdAt: '2026-04-28T15:00:00Z' },
  { _id: 'b-11', title: 'Rajasthan Organic Mission — New Registrations',  description: 'RSOPCB is accepting new applications under Rajasthan Organic Mission for cluster certification of coriander, isabgol and cumin. Eligible FPOs to apply by 20th May 2026.', targetRole: 'FPO Admin', createdAt: '2026-04-22T09:00:00Z' },
  { _id: 'b-12', title: 'Heatwave Advisory — Western Rajasthan',          description: 'IMD has issued a red alert for Barmer, Jaisalmer and Jodhpur districts (45°C+). Farmers advised to reschedule irrigation to early morning hours and avoid fieldwork between 12 PM – 4 PM.', targetRole: 'Farmer',    createdAt: '2026-04-18T08:30:00Z' },
];
